crossref_metadata = {
    "project": {"Description": "Container for project information. Multiple projects may be assigned to a single Grant ID.", "Limits": "required; multiple allowed"},
    "project-title": {"Description": "Title of a project funded by the grant being registered", "Limits": "required; multiple allowed"},
    "description": {"Description": "Used to capture an abstract or description of a project.", "Limits": "optional; multiple allowed"},
    "@xml:lang": {"Description": "Use @xml:lang to identify language for each project-title or description.", "Limits": "optional"},
    "investigators": {"Description": "Container for investigator information", "Limits": "optional"},
    "person": {"Description": "Container for individual investigator details", "Limits": "at least 1 required, multiple allowed (unbounded)"},
    "@role": {"Description": "Available roles are lead_investigator, co-lead_investigator, investigator", "Limits": "required"},
    "@start-date": {"Description": "Date an investigator began work with the project", "Limits": "optional"},
    "@end-date": {"Description": "Date an investigator ended work with the project", "Limits": "optional"},
    "givenName": {"Description": "Given or first name", "Limits": "optional"},
    "familyName": {"Description": "Family or surname", "Limits": "optional"},
    "alternateName": {"Description": "Alias or nickname used by the Investigator", "Limits": "optional"},
    "affiliation": {"Description": "Container for affiliation information", "Limits": "optional, multiple allowed"},
    "institution": {"Description": "Institution an investigator is affiliated with when associated with the project being defined.", "Limits": "1 allowed, use multiple affiliation groups for investigators with multiple affiliations"},
    "@country": {"Description": "ISO 3166-1 alpha 2-letter country code, captures location (country) of affiliation", "Limits": "optional"},
    "ROR": {"Description": "A ROR ID may be supplied to disambiguate affiliation information, expressed as a URL", "Limits": "optional"},
    "ORCID": {"Description": "ORCID ID of the investigator, expressed as a URL", "Limits": "optional"},
    "award-amount": {"Description": "Total overall amount awarded to project", "Limits": "optional"},
    "@currency": {"Description": "ISO 4217 currency for value provided in award-amount", "Limits": "required"},
    "funding": {"Description": "Container for funding information. Use multiple funding sections as needed to specify different funding types", "Limits": "required, multiple allowed"},
    "@amount": {"Description": "Amount of funding provided by funder", "Limits": "optional"},
    "@funding-percentage": {"Description": "Percentage of overall funding", "Limits": "optional"},
    "@funding-type": {"Description": "Type of funding provided, values are limited", "Limits": "required"},
    "@null-amount": {"Description": "Supply for projects where an award amount is missing or can’t be disclosed", "Limits": "optional"},
    "funder-name": {"Description": "Name of the funder", "Limits": "required"},
    "funder-id": {"Description": "Funder identifier from the Funder Registry", "Limits": "required"},
    "funding-scheme": {"Description": "Scheme for grant or award as provided by the funder", "Limits": "optional"},
    "award-dates": {"Description": "Container for date information", "Limits": "optional"},
    "@start-date": {"Description": "Actual start date of award", "Limits": "optional"},
    "@end-date": {"Description": "Actual end date of the award", "Limits": "optional"},
    "@planned-start-date": {"Description": "Planned start date of award", "Limits": "optional"},
    "@planned-end-date": {"Description": "Planned end date of award", "Limits": "optional"},
    "award-number": {"Description": "Funder-supplied award ID / grant number", "Limits": "required"},
    "award-start-date": {"Description": "Start date of grant funding", "Limits": "optional"},
    "relation": {"Description": "Relationship metadata connecting grant to other items (other grants, funded research outputs)", "Limits": "optional"},
    "DOI": {"Description": "DOI being registered", "Limits": "required"},
    "resource": {"Description": "URL of grant landing page", "Limits": "required"}
}
